import {jsPDF} from 'jspdf';
import {regular,bold} from './pdf-font';
import {type Quote,nights} from './model';
export function createPdf(q:Quote,images:Record<string,Uint8Array>={}){
const doc=new jsPDF({compress:true});doc.addFileToVFS('Regular.ttf',regular);doc.addFont('Regular.ttf','Travel','normal');doc.addFileToVFS('Bold.ttf',bold);doc.addFont('Bold.ttf','Travel','bold');const teal=[6,89,96] as const,ink=[28,48,56] as const,muted=[95,113,120] as const;let y=26;const d=q.draft;const label=(id:string)=>q.labels[id]||id;const route=d.cities.map(c=>label(c.city)).join(', ');const money=(n:number)=>'₹ '+n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});const clean=(s:string)=>s.replace(/[–—]/g,'-').replace(/→/g,'to');
function img(url:string|undefined,x:number,top:number,w:number,h:number){if(!url||!images[url])return false;try{const props=doc.getImageProperties(images[url]);const scale=Math.min(w/props.width,h/props.height);doc.addImage(images[url],props.fileType,x+(w-props.width*scale)/2,top+(h-props.height*scale)/2,props.width*scale,props.height*scale,undefined,'FAST');return true;}catch{return false;}}
function header(title:string){doc.setFillColor(...teal);doc.rect(0,0,210,17,'F');doc.setTextColor(255,255,255);doc.setFont('Travel','bold');doc.setFontSize(11);doc.text(clean(title),14,11);y=28;}
function page(title:string){doc.addPage();header(title);}
function room(h:number){if(y+h>274)page('Journey details · continued');}
function text(s:string,size=10,strong=false,color:readonly[number,number,number]=ink){doc.setFont('Travel',strong?'bold':'normal');doc.setFontSize(size);const ls=doc.splitTextToSize(clean(s),180);for(const l of ls){room(size*.5+3);doc.setFont('Travel',strong?'bold':'normal');doc.setFontSize(size);doc.setTextColor(...color);doc.text(l,15,y);y+=size*.5+2;}y+=2;}
function section(s:string){room(25);y+=4;text(s,16,true,teal);}
// Cover: use the configured cover photograph; never substitute an unrelated image.
doc.setFillColor(...teal);doc.rect(0,0,210,297,'F');const cover=q.company.images[1];if(cover&&images[cover])img(cover,0,0,210,185);else if(q.activities.find(a=>a.images[0]))img(q.activities.find(a=>a.images[0])!.images[0],0,0,210,180);
doc.setFillColor(...teal);doc.rect(0,183,210,114,'F');img(q.company.images[0],15,15,50,25);y=203;text('Trip to '+(route.length>100?route.slice(0,97)+'...':route),22,true,[255,255,255]);text(d.start+' to '+d.end+' | '+nights(d.start,d.end)+' nights / '+(nights(d.start,d.end)+1)+' days',11,false,[231,249,247]);text(d.rooms+' rooms | '+d.adults+' adults | '+d.children+' children with bed',11,false,[231,249,247]);text('Prepared for '+d.client,13,true,[255,255,255]);text(q.company.name+' | '+q.company.phone,10,false,[231,249,247]);text('Reference '+q.id.slice(0,8).toUpperCase(),9,false,[231,249,247]);
page('Your travel proposal');img(q.company.images[0],15,24,60,25);y=60;text('Specially prepared for',12,false,muted);text(d.client,25,true);section('Prepared by '+q.company.name);text([q.company.phone,q.company.email,q.company.address].filter(Boolean).join('\n'));y+=8;text('This itinerary is a proposal. Please review the details and inform us of any changes. Services are subject to availability and are confirmed only after supplier confirmation.',11);section('Travel details');text(route,14,true);text(d.start+' - '+d.end);text('Meal plan: '+label(d.meal));text(d.rooms+' rooms; '+d.adults+' adults (including '+d.extraAdults+' extra adults); '+d.children+' children with bed.');
page('Itinerary at a glance');for(const [i,day] of d.days.entries()){room(22);text('Day '+(i+1)+' | '+day.date+' | '+label(day.city),11,true,teal);const names=day.activities.map(id=>q.activities.find(a=>a.id===id)?.name).filter(Boolean);text(names.join(' · ')||'Leisure / activities to be confirmed',10);}
for(const [i,day] of d.days.entries()){const activities=day.activities.map(id=>q.activities.find(a=>a.id===id)).filter(a=>!!a);if(!activities.length){page('Day '+(i+1)+' · '+day.date);text(day.title||label(day.city),20,true,teal);text(day.notes||'Leisure / activities to be confirmed.');continue;}for(const [j,a] of activities.entries()){page('Day '+(i+1)+' · '+day.date+' · '+label(day.city));if(img(a.images[0],0,20,210,83))y=113;text(a.name,20,true,teal);text(a.description||'Activity details to be confirmed.',10);if(j===activities.length-1&&day.notes){section('Day notes');text(day.notes,10);}}}
for(const [i,h] of q.hotels.entries()){page(label(d.cities[i].city)+' · '+d.cities[i].nights+' nights');if(img(h.images[0],15,27,180,82))y=120;text(h.name,22,true,teal);text(h.rating+' star | '+d.rooms+' rooms | '+label(d.meal),11,true);text(h.description||'Accommodation as selected in your quotation.',10);if(h.images[1]&&images[h.images[1]]){room(72);img(h.images[1],15,y,86,65);if(h.images[2])img(h.images[2],108,y,86,65);y+=73;}}
page('Transport & transfers');if(q.vehicle){text(q.vehicle.name,20,true,teal);text(d.vehicles+' vehicle(s) · '+q.vehicle.seats+' seats each · '+d.cabDays+' chargeable days');text('Pickup: '+label(d.pickup));text('Drop: '+label(d.drop));text('Regular transfers and scheduled sightseeing are covered by the daily cab arrangement.');}else text('No daily cab selected.');if(q.transfers.length){section('Special / other transfers');for(const t of q.transfers){text(t.name,12,true);if(t.description)text(t.description);}}else text('No special transfers selected.');
page('Pricing summary');y=45;text('Your journey, ready to go.',23,true,teal);text(d.client+' · '+route,12);y+=12;doc.setFillColor(...teal);doc.roundedRect(15,y,180,44,4,4,'F');doc.setFont('Travel','normal');doc.setFontSize(11);doc.setTextColor(255,255,255);doc.text('TOTAL PACKAGE PRICE',23,y+12);doc.setFont('Travel','bold');doc.setFontSize(27);doc.text(money(q.total),23,y+29);y+=58;text(d.adults+' adults + '+d.children+' children with bed',11);section('Price per guest');for(const r of q.allocation||[]){text(r.category+' ('+r.quantity+')',11,true);text(money(r.unitPrice)+' each | '+money(r.total)+' total'+(r.rounding?' | rounding '+money(r.rounding):''),10);}text('Rooms allocated to regular adults; extra beds to their category. Transport shared equally per guest. Selling adjustments allocated proportionally.',9,false,muted);text('Price calculated on '+q.created.slice(0,10)+'. Subject to availability.',10,false,muted);
if(d.inclusions||d.exclusions){page('Inclusions & exclusions');if(d.inclusions){section('Inclusions');text(d.inclusions);}if(d.exclusions){section('Exclusions');text(d.exclusions);}}
if(q.company.terms){page('Terms & conditions');text(q.company.terms,10);}
page('Thank you');y=90;text('Have a wonderful trip',28,true,teal);text('Thank you for choosing '+q.company.name+'.',13);text('We look forward to helping you make memories in '+route+'.',12);y+=15;section('Need assistance?');text(q.company.name,16,true);text([q.company.phone,q.company.email].filter(Boolean).join('\n'),12);
const count=doc.getNumberOfPages();for(let i=2;i<=count;i++){doc.setPage(i);doc.setDrawColor(221,234,233);doc.line(15,282,195,282);doc.setFont('Travel','normal');doc.setFontSize(8);doc.setTextColor(...muted);doc.text(q.company.name+' | '+q.id.slice(0,8).toUpperCase(),15,289);doc.text(i+' / '+count,195,289,{align:'right'});}return doc.output('arraybuffer');
}
